// Copyright Valve Corporation, All rights reserved.

#ifndef SRC_MATERIALSYSTEM_SHADERAPIDX11_SHADER_API_DX11_GLOBAL_H_
#define SRC_MATERIALSYSTEM_SHADERAPIDX11_SHADER_API_DX11_GLOBAL_H_

#include "shaderapi_global.h"

#endif  // !SRC_MATERIALSYSTEM_SHADERAPIDX11_SHADER_API_DX11_GLOBAL_H_
