// Copyright Valve Corporation, All rights reserved.

#ifndef SE_MATERIALSYSTEM_SHADERAPIDX11_SHADER_API_DX11_GLOBAL_H_
#define SE_MATERIALSYSTEM_SHADERAPIDX11_SHADER_API_DX11_GLOBAL_H_

#include "shaderapi_global.h"

#endif  // !SE_MATERIALSYSTEM_SHADERAPIDX11_SHADER_API_DX11_GLOBAL_H_
